### ISSUE TITLE
Best sale vs lowest price

### ISSUE THREAD

**Issue by CPTpurrfect** [SteamDatabase/steamdb.info-issues#743]
I'd like to suggest to differentiate between "best sale" and "lowest price", as some games have increased their base price the "lowest price" is most likely never going to be attainable again.

The most obvious example being Shovel Knight: Treasure Trove, which has 8,79 € listed as its lowest price at a 33% sale on GOG in 2016, which would have been for 13,19 €.
Since then the price was raised to 49,99 € due to the amount of content added to the game, so the lowest price here isn't a helpful metric outside of statistics any longer, as it doesn't help a user making an informed purchase decision.

My suggestion here is to implement a "best sale", which just uses the records since the latest price raise - as a lower sale most likely will happen should it be lowered, making it unnecessary to filter for this.
Using this metric rather than the currently used "lowest price" metric, which for statistic's sake, I would want to keep, seems to be an option that is more practical for the enduser.

**Comment by xPaw** [comment]
Using base price is not possible because of the way packages work per game (there is not always single "base" package).

I have considered making lowest price a sliding window however, like lowest price in last 3 years or something, because it's affected by inflation in other regions as well. Closing this however, because your idea won't work.
