### ISSUE TITLE
steamdb stopped to work at all on mobile

### ISSUE THREAD

**Issue by mittorn** [SteamDatabase/steamdb.info-issues#768]
- _Browser name and version: _ Firefox 68
- _Device (mobile or desktop):_  Mobile
- _Page where the issue happens:_ any

### Describe the bug
```
Please complete the security check to access SteamDB

Please stand by, while we are checking your browser...
```
Page just refreshes every few seconds

**Comment by xPaw** [comment]
Try a newer Firefox version.

**Comment by mittorn** [comment]
It says "install_failed_insufficient_storage" when trying to install newer version

**Comment by xPaw** [comment]
Well that's a problem with your phone, not the site.

It's not impossible that Cloudflare once again broke something with the security check in Firefox, but I can't really do anything about it, especially when you're using an old browser version.

**Comment by EvgenKo423** [comment]
Yes, you can, but apparently you don't want to: #763.
There are active checks especially for older browsers, so their users could pass the check if an automatic one fails. But the problem is that they are broken and nobody bothers to fix them. Or even test before releasing (yes, Cloudflare, I'm looking at you...).
