### ISSUE TITLE
Steamplay Manifests improvements

### ISSUE THREAD

**Issue by nisehime** [SteamDatabase/steamdb.info-issues#797]
### Feature Description

https://steamdb.info/app/891390/info/

`app_compat_configs` is not convenient to look at, would be better to format it as table like other entries there.
Also, SteamPlay Compatibility Tools table misses aliases https://steamdb.info/app/891390/history/?changeid=20348570
Also x2, misses `require_tool_appid` https://steamdb.info/app/891390/history/?changeid=18517329

**Comment by xPaw** [comment]
I've removed the specialized tables because as you mentioned it's missing various keys and I'm not keen on keeping up to date with them to always add fields to these tables (it's gonna be a long table!)

Instead I have slightly improved rendering arrays in the app info, which makes them easier to read.

**Comment by nisehime** [comment]
Looks good.
