### ISSUE TITLE
SteamDB blocking all VPN access

### ISSUE THREAD

**Issue by hexpwn** [SteamDatabase/steamdb.info-issues#802]
- _Browser:_ Multiple
- _Page where the issue happens:_ all of them

Tested on multiple browsers and also on Windows and Linux.

SteamDB is actively blocking accesses from VPN via Cloudfare.

**Comment by xPaw** [comment]
Only very few VPNs are banned due to a lot of traffic just being abuse, if you use such a VPN I suggest getting a better one.

**Comment by Korb** [comment]
> Only very few VPNs are banned due to a lot of traffic just being abuse, if you use such a VPN I suggest getting a better one.

@xPaw, can you list the VPNs that you think are untrustworthy and should not be used with your site? This will help users choose the right VPN provider without having to give out their credit card details to create accounts and install VPN clients that are obviously unsuitable due to their incompatibility with your service.
